### PR TITLE
updating martian to fix #google/martian/issues/309

### PR DESCRIPTION
**Pull request by phaus**
This change did remove the `flag.Parse` from the martian init function.

### CODE REVIEW

**Comment by phaus** [comment]
Sorry @jba  to bother your again :-/.
To to do another change to have martian compatible with Golang 1.1.7.
Can you please merge and tag this one again? 🙏

**Comment by jba** [comment]
I don't want to make this package require Go 1.17 yet, because Go 1.16 is still supported. 

In a few days we'll release Go 1.18, and then sometime shortly after that I'd be fine with this.

**Comment by jba** [comment]
Pushed tag httpreplay/v1.1.1

**Comment by izturn** [comment]
any progress? the martian v3.3.2 is conflict with corba

**Pull request merged**
